# NAME: Justin Yi
# EMAIL: joostinyi00@gmail.com
# ID: 905123893

default: lab1a.c
	/usr/local/cs/bin/gcc -g -Wall -Wextra -o lab1a lab1a.c
clean:
	rm -rf lab1a lab1a-905123893.tar.gz 
dist: lab1a.c Makefile README
	tar -czf lab1a-905123893.tar.gz lab1a.c Makefile README