# NAME: Justin Yi
# EMAIL: joostinyi00@gmail.com
# ID: 905123893
# Wall Wextra

build:
	-@chmod +x compile.sh 
	-@./compile.sh
dist:
	tar -czvf lab4c-905123893.tar.gz lab4c_tcp.c lab4c_tls.c Makefile README compile.sh
clean:
	rm -rf lab4c_tcp lab4c_tls lab4c-905123893.tar.gz