# NAME: Justin Yi
# EMAIL: joostinyi00@gmail.com
# ID: 905123893

build:
	-@ln -s lab3b.py lab3b
	-@chmod +x lab3b
	-@echo "Success"
dist:
	tar -czvf lab3b-905123893.tar.gz lab3b.py Makefile README
clean:
	rm -rf lab3b lab3b-905123893.tar.gz