# NAME: Justin Yi
# EMAIL: joostinyi00@gmail.com
# ID: 905123893
# Wall Wextra

build:
	-@chmod +x compile.sh 
	-@./compile.sh
check: lab4b
	-@chmod +x check.sh 
	-@./check.sh
dist:
	tar -czvf lab4b-905123893.tar.gz lab4b.c Makefile README compile.sh check.sh
clean:
	rm -rf lab4b lab4b-905123893.tar.gz