# NAME: Justin Yi
# EMAIL: joostinyi00@gmail.com
# ID: 905123893

build:
	/usr/local/cs/bin/gcc -g -Wall -Wextra -o lab3a lab3a.c

dist:
	tar -czvf lab3a-905123893.tar.gz lab3a.c ext2_fs.h Makefile README

clean:
	rm -rf lab3a lab3a-905123893.tar.gz